---
driver:
  name: azurerm
  subscription_id: REPLACE
  location: 'Central US'
  machine_size: Standard_DS5_v2

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.4.56
  client_rb:
    exit_status: :enabled
    environment: kitchen

verifier:
  name: inspec

platforms:
  - name: ubunutu1604
    driver_config:
      image_urn: Canonical:UbuntuServer:16.04-LTS:latest
    transport:
      ssh_key: ~/.ssh/id_kitchen-azurerm

suites:
  - name: pr-test
    run_list:
      - recipe[pr-test::default]
    environments_path: test/environments
    verifier:
      inspec_tests:
        - test/smoke/default

